name: Pull Request Checks

on:
  pull_request:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install pnpm 🔧
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Prettier 💅
        run: pnpm prettier

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install pnpm 🔧
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Lint 💅
        run: pnpm lint

  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install pnpm 🔧
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Check
        run: pnpm check

  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install pnpm 🔧
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Package
        run: pnpm package

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install pnpm 🔧
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Test 🔬
        run: pnpm test
